version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      backend-dependendcies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependendcies:
        patterns:
          - "*"
