name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: xbox_cloud_statistics
          - project: site_generator
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install
      - name: Run black
        run: poetry run black ${{ matrix.project }}
      - name: Run ruff
        run: poetry run ruff check ${{ matrix.project }}
