name: CI (Frontend)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: frontend/**
  pull_request:
    branches: [main]
    paths: frontend/**

env:
  FRONTEND_PATH: frontend

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_PATH }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: results
          path: ${{ env.FRONTEND_PATH }}/results/
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.FRONTEND_PATH }}/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Prepare Nuxt
        run: npx nuxi prepare
      - name: Run formatter
        run: npm run format
      - name: Run linter
        run: npm run lint
      - name: Build
        run: npm run build
