name: Deploy to Pages

on:
  workflow_run:
    workflows: [Run xbox-cloud-statistics]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ github.token }}
  FRONTEND_PATH: frontend
  RESULTS_FILE_NAME: results.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_PATH }}
    steps:
      - uses: actions/checkout@v4
      - name: Download results
        run: |
          gh release download results --pattern ${{ env.RESULTS_FILE_NAME }}
          tar -xzvf ${{ env.RESULTS_FILE_NAME }}
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --only main
      - name: Run site-generator
        run: poetry run site-generator
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.FRONTEND_PATH }}/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
