name: Deploy to Pages

on:
  workflow_run:
    workflows: [Run xbox-cloud-statistics]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FRONTEND_PATH: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: results
          path: ${{ env.FRONTEND_PATH}}/results/
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --only main
      - name: Run site-generator
        run: poetry run site-generator
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.FRONTEND_PATH }}/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
